In [1]:
import numpy as np

In [2]:
np.arange(1,11).reshape([10,1]) + np.zeros(6)

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10.]])

In [3]:
np.arange(1,11).reshape([10,1])

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.arange(1,11).reshape([10,1]) + np.arange(0,6).reshape([1,6])

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11],
       [ 7,  8,  9, 10, 11, 12],
       [ 8,  9, 10, 11, 12, 13],
       [ 9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15]])

In [6]:
np.arange(1,11).reshape([10,1]) * np.arange(1,7).reshape([1,6])

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36],
       [ 7, 14, 21, 28, 35, 42],
       [ 8, 16, 24, 32, 40, 48],
       [ 9, 18, 27, 36, 45, 54],
       [10, 20, 30, 40, 50, 60]])

In [7]:
np.arange(1,11).reshape([10,1]) ** np.arange(1,7).reshape([1,6])

array([[      1,       1,       1,       1,       1,       1],
       [      2,       4,       8,      16,      32,      64],
       [      3,       9,      27,      81,     243,     729],
       [      4,      16,      64,     256,    1024,    4096],
       [      5,      25,     125,     625,    3125,   15625],
       [      6,      36,     216,    1296,    7776,   46656],
       [      7,      49,     343,    2401,   16807,  117649],
       [      8,      64,     512,    4096,   32768,  262144],
       [      9,      81,     729,    6561,   59049,  531441],
       [     10,     100,    1000,   10000,  100000, 1000000]],
      dtype=int32)

In [8]:
(np.arange(-10, 0).reshape([10,1]) + np.arange(0,6).reshape([1,6])) * (-1)

array([[10,  9,  8,  7,  6,  5],
       [ 9,  8,  7,  6,  5,  4],
       [ 8,  7,  6,  5,  4,  3],
       [ 7,  6,  5,  4,  3,  2],
       [ 6,  5,  4,  3,  2,  1],
       [ 5,  4,  3,  2,  1,  0],
       [ 4,  3,  2,  1,  0, -1],
       [ 3,  2,  1,  0, -1, -2],
       [ 2,  1,  0, -1, -2, -3],
       [ 1,  0, -1, -2, -3, -4]])

In [9]:
np.zeros(10).reshape(10,1) + np.arange(1,7).reshape(1,6) 

array([[1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.]])

In [10]:
np.arange(1,7).reshape(1,6) ** np.arange(10).reshape(10,1)

array([[       1,        1,        1,        1,        1,        1],
       [       1,        2,        3,        4,        5,        6],
       [       1,        4,        9,       16,       25,       36],
       [       1,        8,       27,       64,      125,      216],
       [       1,       16,       81,      256,      625,     1296],
       [       1,       32,      243,     1024,     3125,     7776],
       [       1,       64,      729,     4096,    15625,    46656],
       [       1,      128,     2187,    16384,    78125,   279936],
       [       1,      256,     6561,    65536,   390625,  1679616],
       [       1,      512,    19683,   262144,  1953125, 10077696]],
      dtype=int32)